spring:
  cloud:
    stream:
      bindings:
          input:
            destination: some-topic-name
            group: some-group
            content-type: text/plain;charset=UTF-8
            consumer:
              header-mode: raw
  kafka:
    consumer:
      auto-offset-reset: smallest
#spring.cloud.stream.kafka.bindings.input.consumer.resetOffsets=true
#spring.cloud.stream.kafka.bindings.input.consumer.startOffset=earliest
      